AMOMS/urls.py
from django.conf.urls import url, include
from Accounts import views
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', views.IndexView.as_view())
    url(r'^Accounts/', include('Accounts.urls')), # get rid of this later?
    url(r'^Schedule/', include('Schedule.urls')), # get rid of this later?
]

Accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'Accounts'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='login'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^loginRequest/$', views.LoginAccess.as_view(), name='request'),

    url(r'^loginValidate/$', views.validateLogin, name='validate'),


]

Accounts/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db import models


class Employee(User):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    employeeID = models.AutoField(primary_key=True)
    access = (
        ("R", "Receptionist"),
        ("P", "Practitioner"),
        ("A", "Admin"),
    )
    access = models.CharField(max_length=1, choices=access, default="R", null=False)

    def get_absolute_url(self):
        return reverse('patients:home', kwargs={'pk':self.pk})

Accounts/views.py
from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.http import Http404
from .forms import UserForm
from models import Employee
from Schedule import views as Schedviews
from django.http import HttpResponseBadRequest

userAccess = 'R'


class IndexView(generic.ListView):
    template_name = 'Accounts/login.html'

    def get_queryset(self):
        return None



class UserFormView(View):
    form_class = UserForm
    template_name = 'Accounts/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('Accounts:home')

        return render(request, self.template_name, {'form':form})


class LoginAccess(View):
    def determineAccess(self, employee):
        userAccess = employee.access
        if userAccess == 'R':
            redirect(Schedviews.ReceptionistView)
        elif userAccess == 'P':
            redirect(Schedviews.PractionerView)
        elif userAccess == 'A':
            redirect(Schedviews.AdminView)
        else:
            Http404("Access Level Error Occured ")

    def determineAccess(self):
        if userAccess == 'R':
            redirect(Schedviews.ReceptionistView)
        elif userAccess == 'P':
            redirect(Schedviews.PractionerView)
        elif userAccess == 'A':
            redirect(Schedviews.AdminView)
        else:
            Http404("Access Level Error Occured ")


def validateLogin(request):
    email = request.POST.get('email', None)
    password = request.POST.get('password', None)
    print email
    print password
    try:
        employee = Employee.objects.get(username=email)
    except Employee.DoesNotExist:
        return HttpResponseBadRequest("Username or password is incorrect");
    # else:
        # employee = None
    
    print employee
    
    if password == employee.password:
        return redirect(LoginAccess, employee)
    else:
        return HttpResponseBadRequest("Username or password is incorrect");

Accounts/templates/Accounts/AddUser-Adminstrator.html
<!doctype html>
<html>
  <head>
    <link rel= "stylesheet" type="text/css" href="style.css">
  </head>
  <body>
  </body>
  <div id="mySidenav" >

  </div>
  <div id="buttonsMenu">
  <ul>
    <li>
      <a id="Home" href="home" style="position:fixed;top:140px; left:0px; z-index:60;">
      </a>
    </li>
    <li>
      <a id="Reports" href="Reports" style="position:fixed;top:180px; left:0px; z-index:60;">
      </a>
    </li>
  </ul>

  </div>
  <div id="TopMenu" class="TopMenu">
    <a class="CurrentUser"> User:Administrator</a>
    <button id="ReportList">
      <img src="Images/triangle.jpg" style="height:12px;width:12px;position:absolute;top:16px;right:35px">
      Add Users
    </button>
    <div id="SettingsMenu">
      <ul>
        <!--<li><img id="HelpPicture" src="Images/HelpSymbol.jpg"><a id="Help" href="#Lock">Help</a></li>
        <li><img id="SettingsPicture" src="Images/settings.jpg"><a id="Settings" href="#Settings">Settings</a></li>
        <li><img id="LogOutPicture" src="Images/logoutSymbol.jpg"> <a id="LogOut" href="#Log Out">Log Out</a></li>
        <li><img id="LockPicture" src="Images/lockSymbol.jpg"><a id="Lock" href="#Lock">Lock</a></li>-->
      </ul>
    </div>
  </div>

  <div id="FilterMenu">
    <a id="HeadingText" href="NumberofUsers" style="position:fixed; top:126px; left:120px;">1 Active Users</a>
    <label>
      <input type="checkbox" name="Display Inactive" value= "Display">Display Inactive<br>
    </label>
    <select class="SortByList">
      <option value="Sort by" selected disabled>Sort by....</option>
      <option value="New Members">New Members</option>
      <option value="Administrators">Administrators</option>
      <option value="Patients">Patients</option>
      <option value="Receptionist">Receptionist</option>
    </select>
    <button style="position:fixed;right:5%;top:122px" class="SaveButton">
      Save
    </button>
  </div>

  <div  class="bottomMenu">
    <a id="AddUsers" href="Add Users" style="position:absolute; top:0px; left:120px;">Add Users</a>
  </div>

  <div class="AddingAUser">
    <a style="position:absolute; top:170px; left:120px;font-family:Verdana;font-size:15px">Add user</a>

    <label class="FirstName">
     FIRST NAME<br/>
      <input type="text" name="First Name" value="FirstName" onfocus="this.value= this.value=='FirstName'?'':this.value;" onblur="this.value=this.value=''?'name':this.value;">
    </label>
    <label class="LastName">
     LAST NAME<br/>
      <input type="text" name="Last Name" value="Last Name" onfocus="this.value= this.value=='Last Name'?'':this.value;" onblur="this.value=this.value=''?'name':this.value;">
    </label>
    <label class="Email">
      LOGIN EMAIL<br/>
      <input type="text" name="Email" value="Email" onfocus="this.value= this.value=='Email'?'':this.value;" onblur="this.value=this.value=''?'name':this.value;">
    </label>
    <label class="LoginPassword">LOGIN PASSWORD<br/>
    <input type="text" name="Password" value="Password" onfocus="this.value=this.value=='Password'?'':this.value;"
onblur="this.value=this.value=''?'Password'?'':this.Password;">
    </label>
    <select class="AccessList">

      <option disabled selected>Select access....</option>
      <option value="New Members">Administrator</option>
      <option value="Administrators">Physician</option>
      <option value="Patients">Receptionist</option>
      <option value="Receptionist">Patient</option>
    </select>
    <table border="0" class="UserTable">
      <tr>
        <th align="left">NAME</th>
        <th align="left">EMAIL</th>
        <th align="left">ACCESS LEVEL</th>
        <th align="left">PERMISSION/USER STATUS</th>
      </tr>
      <tr>
        <td bgcolor="#ffffff" ><span style="color:#14a4eb;">Jorge Castillo</span>
        </td>
        <td bgcolor="#ffffff">
          Jorge@gmail.com
        </td>
        <td bgcolor="#ffffff">
          Phys.Md/DD
        </td>
        <td bgcolor="#ffffff">
          Admin
          Status
        </td>
        <button style="position:fixed;right:5%;top:265px" class="SaveButton">
          Deactivate
        </button>
      </tr>
    </table>
  </div>

  <button class="AddButton" style="position:absolute;                           top:199px;                             left:930px;">
    Add
  </button>

</html>

Accounts/templates/Accounts/AppointmentList-Admin.html
<html>
  <head>
    <link rel= "stylesheet" type="text/css" href="Report.css">
    <script type="text/javascript" src="https://formden.com/static/cdn/formden.js"></script>
    <link rel="stylesheet" href="https://formden.com/static/cdn/font-awesome/4.4.0/css/font-awesome.min.css" />
  </head>
  <body style="background-color:#white">

    <div id="mySidenav" >

    </div>
    <div class="buttonsMenu">
      <ul>
        <li>
          <a id="Home" href="home" style="position:fixed;top:140px; left:0px; z-index:60;">
          </a>
        </li>
        <li>
          <a id="Reports" href="Reports" style="position:fixed;top:180px; left:0px; z-index:60;">
          </a>
        </li>
      </ul>

    </div>
    <div id="TopMenu" class="TopMenu">
      <a class="CurrentUser"> User:Administrator</a>
      <div id="SettingsMenu">
        <ul>
          <li><img id="HelpPicture" src="Images/HelpSymbol.jpg"><a id="Help" href="#Lock">Help</a></li> 
          <li><img id="SettingsPicture" src="Images/settings.jpg"><a id="Settings" href="#Settings">Settings</a></li>
          <li><img id="LogOutPicture" src="Images/logoutSymbol.jpg"> <a id="LogOut" href="#Log Out">Log Out</a></li>
          <li><img id="LockPicture" src="Images/lockSymbol.jpg"><a id="Lock" href="#Lock">Lock</a></li> 
        </ul>
      </div>
    </div>
    <div  class="bottomMenu">
      <a id="AddUsers" href="Add Users" style="position:absolute; top:32px; left:120px;">Appointments List</a>
      <button id="ReportList">
        <img src="Images/triangle.jpg" style="height:12px;width:12px;position:absolute;top:16px;right:35px">
        Report List
      </button>
    </div>
    <input type="text" id="SearchBar" onkeyup="myFunction()" placeholder="Search for appointments.." title="Type in a name">
    <select class="FilterList">
      <option disabled selected>Select access....</option>
      <option value="Most Recent Appointments">Most Recent</option>
      <option value="Oldest">Oldest</option>
      <option value="HightoLow">High to Low ID</option>
      <option value="LowtoHigh">Low to High ID</option>
    </select>
      <table border="0" class="UserTable">
        <tr>
          <th align="left" id="AptID" width="8%">APPOINTMENT ID</th>
          <th align="left" id="PatientID" width="7%">PATIENT ID</th>
          <th align="left" id="EmployeeID" width="30%">Practitioner Name</th> 
          <th align="left" id="CheckIn" width=
              "9%">CHECK IN TIME</th>
          <th align="left" id="CheckOut" width="9%">CHECK OUT TIME</th>
          <th align="left" id="AppStart" width=
              "9%">APP. START</th>
          <th align="left" id="AppEnd">APP. END</th>
        </tr>
        <tr>
        </tr>
      </table>

  </body>
</html>

Accounts/templates/Accounts/AppointmentList-Receptionist.html
<html>
  <head>
    <link rel= "stylesheet" type="text/css" href="Report.css">
    <link rel= "stylesheet" type="text/css" href="Report.css">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />
  </head>
  <body style="background-color:#white">

    <div id="mySidenav" >

    </div>
    <div class="buttonsMenu">
      <ul>
        <a href="Home-Receptionist.html">
          <li id="Home" href="home" style="position:fixed;top:140px; left:0px; z-index:60;">
          </li>
        </a>
        <a href="ReportPage-Receptionist.html">
          <li id="ReportsButton" href="Reports" style="position:fixed;top:180px; left:0px; z-index:60;">
          </li>
        </a>
        <li id="ScheduleButton" href="Reports" style="position:fixed;top:220px;left:0px;z-index:60;">
        </li>
        <li id="AddUsersButton" href="Reports" style="position:fixed;top:260px;left:0px;z-index:60;">
        </li>
      </ul>

    </div>
    <div id="TopMenu" class="TopMenu">
      <a class="CurrentUser"> User:Receptionist</a>
      <div id="SettingsMenu">
        <ul>
          <li><img id="HelpPicture" src="Images/HelpSymbol.jpg"><a id="Help" href="#Lock">Help</a></li> 
          <li><img id="SettingsPicture" src="Images/settings.jpg"><a id="Settings" href="#Settings">Settings</a></li>
          <li><img id="LogOutPicture" src="Images/logoutSymbol.jpg"> <a id="LogOut" href="#Log Out">Log Out</a></li>
          <li><img id="LockPicture" src="Images/lockSymbol.jpg"><a id="Lock" href="#Lock">Lock</a></li> 
        </ul>
      </div>
    </div>
    <div  class="bottomMenu">
      <a id="AddUsers" href="Add Users" style="position:absolute; top:32px; left:120px;">Appointments List</a>
    </div>
    <div class="bootstrap-iso" style="position:absolute;top:23%;left:70%;z-index:50;height:0;width:350px;">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <form action="https://formden.com/post/MlKtmY4x/" class="form-horizontal" method="post">
              <div class="form-group ">
                <div class="col-sm-10">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-calendar">
                      </i>
                    </div>
                    <input class="form-control" id="dateFrom1" name="date" placeholder="Date From" type="text"/>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="bootstrap-iso" style="position:absolute;top:23%;left:80%;z-index:50;height:0;width:400px;">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <form action="https://formden.com/post/MlKtmY4x/" class="form-horizontal" method="post">
              <div class="form-group ">
                <div class="col-sm-10">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-calendar">
                      </i>
                    </div>
                    <input class="form-control" id="DateTo1" name="date" placeholder="Date To" type="text"/>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <buton class ="AddButton" style="position:absolute;top:23%;right:3%;z-index:40;">
      Apply
    </buton>
    <input type="text" id="SearchBar" onkeyup="myFunction()" placeholder="Search for appointments.." title="Type in a name">
    <select class="FilterList">
      <option disabled selected>Select access....</option>
      <option value="Most Recent Appointments">Most Recent</option>
      <option value="Oldest">Oldest</option>
      <option value="HightoLow">High to Low ID</option>
      <option value="LowtoHigh">Low to High ID</option>
    </select>
    <table border="0" class="UserTable">
      <tr>
        <th align="left" id="AptID" width="8%">APPOINTMENT ID</th>
        <th align="left" id="PatientID" width="7%">PATIENT ID</th>
        <th align="left" id="EmployeeID" width="30%">Practitioner Name</th> 
        <th align="left" id="CheckIn" width=
"9%">CHECK IN TIME</th>
        <th align="left" id="CheckOut" width="9%">CHECK OUT TIME</th>
        <th align="left" id="AppStart" width=
"9%">APP. START</th>
        <th align="left" id="AppEnd">APP. END</th>
      </tr>
      <tr>
      </tr>
    </table>

  </body>
</html>

Accounts/templates/Accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title %}AMOMS{% endblock %}</title>
     {% load staticfiles %}
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
     <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
     <link rel="stylesheet" type="text/css" href="{% static 'Accounts/style.css' %}" />
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
     <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Logo would go here -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Accounts:home' %}">AMOMS</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'Schedule:index' %}">
                        Schedules
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'Schedule:index' %}">
                        Patients
                    </a>
                </li>

            </ul>

            <ul class="nav navbar-nav navbar-right">

                <li class="">
                    <a href="{% url 'Accounts:register' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Employee
                    </a>
                </li>

                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Accounts/templates/Accounts/form-template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>

{% endfor %}

Accounts/templates/Accounts/home.html
{% extends 'Accounts/base.html' %}
{% block title %} Home {% endblock %}

{% block body %}



{% endblock %}

Accounts/templates/Accounts/index.html
<!DOCTYPE html>
<html lang = 'en'>
<body>
<div class="button">
    <a class="button" href="{% url 'Accounts:home' %}">HOME</a>
</div>


</body>
</html>

Accounts/templates/Accounts/login.html
<!DOCTYPE html> {% load staticfiles %}
<html>

<head>
  <title>{%block title %}AMOMS{% endblock %}</title>

  <link rel="stylesheet" type="text/css" href="{% static 'Accounts/Login.css' %}">
  <link type="text/javscript" src="Slide.js">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  {% csrf_token %}
</head>

<body>


  <div id="Header">
    <img src="{% static 'Accounts/images/SymbolLabel.jpg' %}" class="HomeSymbol">
  </div>

  <div class="Features">
    <img class="mySlides" src="{% static 'Accounts/images/SchedulePatients.jpg' %}" style="width:70%">
    <img class="mySlides" src="{% static 'Accounts/images/PrescriptionPatients.jpg' %}" style="width:70%">
    <img class="mySlides" src="{% static 'Accounts/images/PrescriptionEditor.jpg' %}" style="width:70%">
    <button style="position:absolute;top:40%;left:-5%;" class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
    <button style="position:absolute;top:40%;left:70%;" class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
  </div>

  <div class="LogScreen">
    <a style="position:absolute;top:10%;left:45%;color:black;font-weight:bold;">Log In</a>
    <a id="subHeader" style="position: absolute;                   top:25%;right:10%;">Forgot your Login Email?</a>
    <a id="subHeader" style="position: absolute;                   top:40%;right:10%;">Forgot your Password?</a>
    <label class="Emailtype">
    Email<br>
    <input  type="text" id="email">
  </label>
    <label class="Passwordtype">
      Password<br>
      <input  type="password" id="password">
    </label>
    <br>
    <span id="error" style="color:red"></span>
    <button class="LoginButton" type='submit' onclick="saveinfo()">
    LOGIN
  </button>
  </div>

  <div class="HelpBar">
    <label class="HelpBarButtons">
  <a id="date" href="date" style="text-decoration:none">@2017 software system name |</a>
    <a id="sitemap" href="style" style="text-decoration:none">Site Map |</a>
    <a id="sitemap" href="style" style="text-decoration:none">Terms |</a>
    <a id="sitemap" href="style" style="text-decoration:none">Privacy Policy |</a>
      <a id="sitemap" href="style" style="text-decoration:none">software system name Status</a>
  </label>
  </div>

  <script>
    var slideIndex = 1;
    showDivs(slideIndex);

    function plusDivs(n) {
      showDivs(slideIndex += n);
    }

    function showDivs(n) {
      var i;
      var x = document.getElementsByClassName("mySlides");
      if (n > x.length) { slideIndex = 1 }
      if (n < 1) { slideIndex = x.length }
      for (i = 0; i < x.length; i++) {
        x[i].style.display = "none";
      }
      x[slideIndex - 1].style.display = "block";
    }

    function saveinfo() {
      var url = "{% url 'Accounts:validate' %}";
      var csrftoken = $("[name=csrfmiddlewaretoken]").val();

      $.ajaxSetup({
        beforeSend: function (xhr, settings) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      });
      
      $("#error").hide();
      $.ajax({
        method: 'POST',
        url: url,
        data: {
          email: $('#email').val(),
          password: $('#password').val()
        },
        dataType: 'json',
        success: function (response) {
          
        },
        error: function (a,b,statusText) {
          $("#error").show().text(a.responseText)
        }
      })
    }
  </script>
</body>

</html>

Accounts/templates/Accounts/registration_form.html
{% block title %} Register {% endblock %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post">
                        {% csrf_token %}
                        {% include 'Accounts/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}