AMOMS/urls.py
from django.conf.urls import url, include
from Accounts import views
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', views.IndexView.as_view())
    url(r'^Accounts/', include('Accounts.urls')), # get rid of this later?
    url(r'^Schedule/', include('Schedule.urls')), # get rid of this later?
]

Schedule/urls.py
from django.conf.urls import url
from . import views

app_name = 'Schedule'

urlpatterns = [


    url(r'^receptionist/$', views.ReceptionistView.as_view(), name='receptionist'),

    url(r'^practitioner/$', views.PractitionerView.as_view(), name='practitioner'),

    url(r'^admin/$', views.AdminView.as_view(), name='admin'),

    url(r'^admin/register/$', views.AdminRegister.as_view(), name='register'),

    url(r'^receptionist/home/$', views.ReceptionistHome.as_view(), name='rhome'),

    url(r'^admin/home/$', views.AdminHome.as_view(), name='ahome'),

    url(r'^admin/callback/$', views.AdminCallBack.as_view(), name='acallback'),

    url(r'^receptionist/callback/$', views.ReceptionistCallBack.as_view(), name='rcallback'),

    url(r'^admin/reports/$', views.AdminReports.as_view(), name='areports'),

    url(r'^receptionist/reports/$', views.ReceptionistReports.as_view(), name='rreports'),

    url(r'^admin/MissedAppointments/$', views.AdminMissedAppointments.as_view(), name='amissed'),

    url(r'^receptionist/MissedAppointments/$', views.ReceptionistMissedAppointments.as_view(), name='rmissed'),

    url(r'^receptionist/AppointmentReminder/$', views.ReceptionistAppointmentReminder.as_view(), name='rreminder'),

    url(r'^admin/AppointmentReminder/$', views.AdminAppointmentReminder.as_view(), name='areminder'),

    url(r'^receptionist/NewPatient/$', views.ReceptionistAddPatient.as_view(), name='raddpatient'),

    url(r'^receptionist/PatientView/$', views.ReceptionistPatientView.as_view(), name='rpatient'),

    url(r'^receptionist/PatientsList/$', views.ReceptionistPatientsView.as_view(), name='rpatients'),

    url(r'^receptionist/schedule/$', views.ReceptionistSchedule.as_view(), name='rschedule'),
]

Schedule/models.py
from __future__ import unicode_literals

from django.db import models
from Accounts.models import Employee
from django.core.urlresolvers import reverse


class Schedule(models.Model):
    scheduleID = models.AutoField(primary_key=True)
    startTime = models.DateTimeField()
    endTime = models.DateTimeField()
    employeeID = models.ForeignKey(Employee)


class Prescription(models.Model):
    prescriptionID = models.AutoField(primary_key=True)
    prescriptionTxt = models.TextField()
    printTime = models.DateTimeField()
    employeeID = models.ForeignKey(Employee)
    createdTime = models.DateTimeField()
    prescriptionTitle = models.CharField(max_length=250)


class Diagnoses(models.Model):
    diagnosesID = models.AutoField(primary_key=True)
    diagnosesName = models.TextField()
    diagnosesDateBegin = models.DateTimeField()
    diagnosesDateEND = models.DateTimeField()
    diagnosesSeverity = models.PositiveIntegerField()


class Patient(models.Model):
    patientID = models.AutoField(primary_key=True)
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    middleI = models.CharField(max_length=1, null=True)
    dob = models.DateField()
    gender = (
        ("M", "Male"),
        ("F", "Female"),
    )
    gender = models.CharField(max_length=1, choices=gender, default="M", null=False)
    fileKey = models.CharField(max_length=30, null=True)
    maritalStat = models.CharField(max_length=30, null=True)
    phone = models.PositiveIntegerField( null=True)
    occupation = models.CharField(max_length=100)
    email = models.EmailField()
    mailingAdd = models.CharField(max_length=250)
    children = models.PositiveIntegerField()
    medicalHistory = models.TextField()

    def get_absolute_url(self):
        return reverse('patients:details', kwargs={'pk':self.pk})


class Notes(models.Model):
    noteID = models.AutoField(primary_key=True)
    patientID = models.ForeignKey(Patient, on_delete=models.CASCADE)
    noteText = models.TextField(max_length=1000)

    def get_absolute_url(self):
        return reverse('patients:details', kwargs={'pk':self.pk})


class Appointment(models.Model):
    appointmentID = models.AutoField(primary_key=True)
    patientID = models.ForeignKey(Patient)
    employeeID = models.ForeignKey(Employee)
    scheduledDate = models.DateField()
    scheduledTime = models.DateTimeField()
    notes = models.TextField()
    checkinTime = models.DateTimeField()
    checkoutTime = models.DateTimeField()
    appointmentStart = models.DateTimeField()
    appointmentEnd = models.DateTimeField()

Schedule/forms.py
from .models import Employee
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Employee
        fields = ['username', 'email', 'password', ]

Schedule/views.py
from django.views import generic
from .models import Patient


class ReceptionistSchedule(generic.ListView):
    template_name = 'Schedule/Schedule.html'

    def get_queryset(self):
        return None
        
class ReceptionistView(generic.ListView):
    template_name = 'Schedule/AppointmentList-Receptionist.html'

    def get_queryset(self):
        return None


class PractitionerView(generic.ListView):
    template_name = 'Schedule/AppointmentList-Receptionist.html'

    def get_queryset(self):
        return None


class AdminView(generic.ListView):
    template_name = 'Schedule/AppointmentList-Admin.html'

    def get_queryset(self):
        return None


class ReceptionistHome(generic.ListView):
    template_name = 'Schedule/Home-Receptionist.html'

    def get_queryset(self):
        return None


class AdminHome(generic.ListView):
    template_name = 'Schedule/Home-Administrator.html'

    def get_queryset(self):
        return None


class AdminReports(generic.ListView):
    template_name = 'Schedule/ReportPage-Admin.html'

    def get_queryset(self):
        return None


class ReceptionistReports(generic.ListView):
    template_name = 'Schedule/ReportPage-Receptionist.html'

    def get_queryset(self):
        return None


class AdminMissedAppointments(generic.ListView):
    template_name = 'Schedule/MissedAppointments-Admin.html'

    def get_queryset(self):
        return None


class ReceptionistMissedAppointments(generic.ListView):
    template_name = 'Schedule/MissedAppointments-Receptionist.html'

    def get_queryset(self):
        return None


class AdminCallBack(generic.ListView):
    template_name = 'Schedule/CallBack-Admin.html'

    def get_queryset(self):
        return None


class ReceptionistCallBack(generic.ListView):
    template_name = 'Schedule/CallBack-Receptionist.html'

    def get_queryset(self):
        return None


class AdminAppointmentReminder(generic.ListView):
    template_name = 'Schedule/AppointmentReminder-Admin.html'

    def get_queryset(self):
        return None


class ReceptionistAppointmentReminder(generic.ListView):
    template_name = 'Schedule/AppointmentReminder-Receptionist.html'

    def get_queryset(self):
        return None


class ReceptionistAddPatient(generic.ListView):
    template_name = 'Schedule/AddUsers-Receptionist.html'

    def get_queryset(self):
        return None


class ReceptionistPatientView(generic.ListView):
    template_name = 'Schedule/PatientProfile-Receptionist.html'

    def get_queryset(self):
        return None


class ReceptionistPatientsView(generic.ListView):
    template_name = 'Schedule/PatientProfiles-Receptionist.html'

    def get_queryset(self):
        patients = Patient.objects.all()
        return patients



class AdminRegister(generic.ListView):
    template_name = 'Schedule/AddUser-Adminstrator.html'

    def get_queryset(self):
        return None

Schedule/templates/Schedule/AddUser-Adminstrator.html
<!doctype html>
<html>
{% load staticfiles %}
  <head>
    <link rel= "stylesheet" type="text/css" href="{% static 'Schedule/style.css' %}">
  </head>
  <body>
  </body>
  <div id="mySidenav" >

  </div>
  <div id="buttonsMenu">
  <ul>
      <a href="{% url 'Schedule:ahome' %}">
        <li id="Home" href="{% url 'Schedule:ahome' %}" style="position:fixed;top:140px; left:0px; z-index:60;">
        </li>
      </a>

      <a href="{% url 'Schedule:rhome' %}">
        <li id="ReceptionistButton" href="{% url 'Schedule:rhome' %}" style="position:fixed;top:180px; left:0px; z-index:60;">
        </li>
      </a>

      <a href="{% url 'Schedule:ahome' %}">
        <li id="PratitionerButton" href="{% url 'Schedule:ahome' %}" style="position:fixed;top:220px;left:0px;z-index:60;">
        </li>
      </a>

      <a href="{% url 'Schedule:register' %}">
        <li id="AddUsersButton" href="{% url 'Schedule:register' %}" style="position:fixed;top:260px;left:0px;z-index:60;">
        </li>
      </a>
  </ul>

  </div>
  <div id="TopMenu" class="TopMenu">
    <a class="CurrentUser"> User:Administrator</a>
    <button id="ReportList">
      <img src="{% static 'Schedule/images/triangle.jpg' %}" style="height:12px;width:12px;position:absolute;top:16px;right:35px">
      Add Users
    </button>
    <div id="SettingsMenu">
      <ul>
        <li><img id="HelpPicture" src="{% static 'Schedule/images/HelpSymbol.jpg' %}"><a id="Help" href="#Lock">Help</a></li>
        <li><img id="SettingsPicture" src="{% static 'Schedule/images/settings.jpg' %}"><a id="Settings" href="#Settings">Settings</a></li>
        <li><img id="LogOutPicture" src="{% static 'Schedule/images/logoutSymbol.jpg' %}"> <a id="LogOut" href="#Log Out">Log Out</a></li>
        <li><img id="LockPicture" src="{% static 'Schedule/images/lockSymbol.jpg' %}"><a id="Lock" href="#Lock">Lock</a></li>
      </ul>
    </div>
  </div>

  <div id="FilterMenu">
    <a id="HeadingText" href="NumberofUsers" style="position:fixed; top:126px; left:120px;">1 Active Users</a>
    <label>
      <input type="checkbox" name="Display Inactive" value= "Display">Display Inactive<br>
    </label>
    <select class="SortByList">
      <option value="Sort by" selected disabled>Sort by....</option>
      <option value="New Members">New Members</option>
      <option value="Administrators">Administrators</option>
      <option value="Patients">Patients</option>
      <option value="Receptionist">Receptionist</option>
    </select>
    <button style="position:fixed;right:5%;top:122px" class="SaveButton">
      Save
    </button>
  </div>

  <div  class="bottomMenu">
    <a id="AddUsers" href="{% url 'Schedule:register' %}" style="position:absolute; top:0px; left:120px;">Add Users</a>
  </div>

  <div class="AddingAUser">
    <a style="position:absolute; top:170px; left:120px;font-family:Verdana;font-size:15px">Add user</a>

    <label class="FirstName">
     FIRST NAME<br/>
      <input type="text" name="First Name" value="FirstName" onfocus="this.value= this.value=='FirstName'?'':this.value;" onblur="this.value=this.value=''?'name':this.value;">
    </label>
    <label class="LastName">
     LAST NAME<br/>
      <input type="text" name="Last Name" value="Last Name" onfocus="this.value= this.value=='Last Name'?'':this.value;" onblur="this.value=this.value=''?'name':this.value;">
    </label>
    <label class="Email">
      LOGIN EMAIL<br/>
      <input type="text" name="Email" value="Email" onfocus="this.value= this.value=='Email'?'':this.value;" onblur="this.value=this.value=''?'name':this.value;">
    </label>
    <label class="LoginPassword">LOGIN PASSWORD<br/>
    <input type="text" name="Password" value="Password" onfocus="this.value=this.value=='Password'?'':this.value;"
onblur="this.value=this.value=''?'Password'?'':this.Password;">
    </label>
    <select class="AccessList">

      <option disabled selected>Select access....</option>
      <option value="New Members">Administrator</option>
      <option value="Administrators">Physician</option>
      <option value="Patients">Receptionist</option>
      <option value="Receptionist">Patient</option>
    </select>
    <table border="0" class="UserTable">
      <tr>
        <th align="left">NAME</th>
        <th align="left">EMAIL</th>
        <th align="left">ACCESS LEVEL</th>
        <th align="left">PERMISSION/USER STATUS</th>
      </tr>
      <tr>
        <button style="position:fixed;right:5%;top:265px" class="SaveButton">
          Deactivate
        </button>
      </tr>
    </table>
  </div>

  <button class="AddButton" style="position:absolute;                           top:199px;                             left:930px;">
    Add
  </button>

</html>

Schedule/templates/Schedule/AppointmentList-Receptionist.html
<html>
{% load staticfiles %}
  <head>
    <link rel= "stylesheet" type="text/css" href="{% static 'Schedule/Report.css' %}">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />
  </head>
  <body style="background-color:#white">

    <div id="mySidenav" >

    </div>
    <div class="buttonsMenu">
      <ul>
        <a href="{% url 'Schedule:rhome' %}">
          <li id="Home" href="{% url 'Schedule:rhome' %}" style="position:fixed;top:140px; left:0px; z-index:60;">
          </li>
        </a>

        <a href="{% url 'Schedule:rreports' %}">
          <li id="ReportsButton" href="{% url 'Schedule:rreports' %}" style="position:fixed;top:180px; left:0px; z-index:60;">
          </li>
        </a>

        <a href="{% url 'Schedule:rhome' %}">
          <li id="ScheduleButton" href="{% url 'Schedule:rhome' %}" style="position:fixed;top:220px;left:0px;z-index:60;">
          </li>
        </a>

          <a href="{% url 'Schedule:raddpatient' %}">
            <li id="AddUsersButton" href="{% url 'Schedule:raddpatient' %}" style="position:fixed;top:260px;left:0px;z-index:60;">
            </li>
          </a>

          <a href="{% url 'Schedule:rpatients' %}">
            <li id="PatientProfiles" href="{% url 'Schedule:rpatients' %}" style="position:fixed;top:300px;left:0px;z-index:60;">
            </li>
          </a>
      </ul>

    </div>
    <div id="TopMenu" class="TopMenu">
      <a class="CurrentUser"> User:Receptionist</a>
      <div id="SettingsMenu">
        <ul>
          <li><img id="HelpPicture" src="{% static 'Schedule/images/HelpSymbol.jpg' %}"><a id="Help" href="#Lock">Help</a></li>
          <li><img id="SettingsPicture" src="{% static 'Schedule/images/settings.jpg' %}"><a id="Settings" href="#Settings">Settings</a></li>
          <li><img id="LogOutPicture" src="{% static 'Schedule/images/logoutSymbol.jpg' %}"> <a id="LogOut" href="#Log Out">Log Out</a></li>
          <li><img id="LockPicture" src="{% static 'Schedule/images/lockSymbol.jpg' %}"><a id="Lock" href="#Lock">Lock</a></li>
        </ul>
      </div>
    </div>
    <div  class="bottomMenu">
    </div>
    <div class="bootstrap-iso" style="position:absolute;top:23%;left:70%;z-index:50;height:0;width:350px;">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <form action="https://formden.com/post/MlKtmY4x/" class="form-horizontal" method="post">
              <div class="form-group ">
                <div class="col-sm-10">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-calendar">
                      </i>
                    </div>
                    <input class="form-control" id="dateFrom1" name="date" placeholder="Date From" type="text"/>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="bootstrap-iso" style="position:absolute;top:23%;left:80%;z-index:50;height:0;width:400px;">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <form action="https://formden.com/post/MlKtmY4x/" class="form-horizontal" method="post">
              <div class="form-group ">
                <div class="col-sm-10">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-calendar">
                      </i>
                    </div>
                    <input class="form-control" id="DateTo1" name="date" placeholder="Date To" type="text"/>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <button class ="AddButton" style="position:absolute;top:23%;right:3%;z-index:40;">
      Apply
    </button>
    <input type="text" id="SearchBar" onkeyup="myFunction()" placeholder="Search for appointments.." title="Type in a name">
    <select class="FilterList">
      <option disabled selected>Select access....</option>
      <option value="Most Recent Appointments">Most Recent</option>
      <option value="Oldest">Oldest</option>
      <option value="HightoLow">High to Low ID</option>
      <option value="LowtoHigh">Low to High ID</option>
    </select>
    <table border="0" class="UserTable">
      <tr>
        <th align="left" id="AptID" width="8%">APPOINTMENT ID</th>
        <th align="left" id="PatientID" width="7%">PATIENT ID</th>
        <th align="left" id="EmployeeID" width="30%">Practitioner Name</th> 
        <th align="left" id="CheckIn" width=
"9%">CHECK IN TIME</th>
        <th align="left" id="CheckOut" width="9%">CHECK OUT TIME</th>
        <th align="left" id="AppStart" width=
"9%">APP. START</th>
        <th align="left" id="AppEnd">APP. END</th>
      </tr>
      <tr>
      </tr>
    </table>

  </body>
</html>

Schedule/templates/Schedule/CallBack-Receptionist.html
<html>
{% load staticfiles %}
  <head>
    <link rel= "stylesheet" type="text/css" href="{% static 'Schedule/Report.css' %}">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />
  </head>
  <body style="background-color:#white">
    <div id="mySidenav" >
    </div>
    <div class="buttonsMenu">
      <ul>
        <a href="{% url 'Schedule:rhome' %}">
          <li id="Home" href="{% url 'Schedule:rhome' %}" style="position:fixed;top:140px; left:0px; z-index:60;">
          </li>
        </a>

        <a href="{% url 'Schedule:rreports' %}">
          <li id="ReportsButton" href="{% url 'Schedule:rreports' %}" style="position:fixed;top:180px; left:0px; z-index:60;">
          </li>
        </a>

        <a href="{% url 'Schedule:rschedule' %}">
          <li id="ScheduleButton" href="{% url 'Schedule:rschedule' %}" style="position:fixed;top:220px;left:0px;z-index:60;">
          </li>
        </a>

          <a href="{% url 'Schedule:raddpatient' %}">
            <li id="AddUsersButton" href="{% url 'Schedule:raddpatient' %}" style="position:fixed;top:260px;left:0px;z-index:60;">
            </li>
          </a>

          <a href="{% url 'Schedule:rpatients' %}">
            <li id="PatientProfiles" href="{% url 'Schedule:rpatients' %}" style="position:fixed;top:300px;left:0px;z-index:60;">
            </li>
          </a>
      </ul>

    </div>
    <div id="TopMenu" class="TopMenu">
      <a class="CurrentUser"> User:Receptionist</a>
      <div id="SettingsMenu">
        <ul>
          <li><img id="HelpPicture" src="{% static 'Schedule/images/HelpSymbol.jpg' %}"><a id="Help" href="#Lock">Help</a></li>
          <li><img id="SettingsPicture" src="{% static 'Schedule/images/settings.jpg' %}"><a id="Settings" href="#Settings">Settings</a></li>
          <li><img id="LogOutPicture" src="{% static 'Schedule/images/logoutSymbol.jpg' %}"> <a id="LogOut" href="#LogOut">Log Out</a></li>
          <li><img id="LockPicture" src="{% static 'Schedule/images/lockSymbol.jpg' %}"><a id="Lock" href="#Lock">Lock</a></li>
        </ul>
      </div>
    </div>
    
    <div  class="bottomMenu">
      <a id="AddUsers"  style="position:absolute; top:32px; left:120px;">Appointment Remainders</a>
    </div>
    <input type="text" id="SearchBar" onkeyup="myFunction()" placeholder="Search for appointments.." title="Type in a name">
  <div class="bootstrap-iso" style="position:absolute;top:23%;left:70%;z-index:50;height:0;width:350px;">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <form action="https://formden.com/post/MlKtmY4x/" class="form-horizontal" method="post">
              <div class="form-group ">
                <div class="col-sm-10">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-calendar">
                      </i>
                    </div>
                    <input class="form-control" id="dateFrom" name="date" placeholder="Date From" type="text"/>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="bootstrap-iso" style="position:absolute;top:23%;left:80%;z-index:50;height:0;width:400px;">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <form action="https://formden.com/post/MlKtmY4x/" class="form-horizontal" method="post">
              <div class="form-group ">
                <div class="col-sm-10">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-calendar">
                      </i>
                    </div>
                    <input class="form-control" id="DateTo" name="date" placeholder="Date To" type="text"/>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <burton class ="AddButton" style="position:absolute;top:23%;right:3%;z-index:40;">
    Apply
    </burton>
    <select class="FilterList">
      <option disabled selected>Select access....</option>
      <option value="Most Recent Appointments">Most Recent</option>
      <option value="Oldest">Oldest</option>
      <option value="HightoLow">High to Low ID</option>
      <option value="LowtoHigh">Low to High ID</option>
    </select>
    <table border="0" class="UserTable">
      <tr>
        <th align="left" width="10%" id="AptID">APPOINTMENT ID</th>
        <th align="left" width="10%" id="PatientID">PATIENT ID</th>
        <th align="left" width="30%" id="PractitionerName">Practitioner Name</th> 
        <th align="left" width="10%" id="ApptDate">APPT. DATE</th>
        <th align="left" id="Reason">REASON FOR VISIT</th>
      </tr>
      <tr>
      </tr>
    </table>

  </body>
</html>
<script>
  $(document).ready(function() {
    $("#datepicker").datepicker();
  });
</script>
<script>
  $(document).ready(function(){
    var date_input=$('input[name="date"]'); //our date input has the name "date"
    var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
    date_input.datepicker({
      format: 'mm/dd/yyyy',
      container: container,
      todayHighlight: true,
      autoclose: true,
    })
  })
</script>

Schedule/templates/Schedule/Home-Receptionist.html
<html>
{% load staticfiles %}
  <head>
    <link rel= "stylesheet" type="text/css" href="{% static 'Schedule/HomeStyle.css' %}">
  </head>
  <body style="background-color:#dfdfdf">
    <div id="mySidenav" >
    </div>
    <div class="buttonsMenu">
      <ul>

        <a href="{% url 'Schedule:rhome' %}">
          <li id="Home" href="{% url 'Schedule:rhome' %}" style="position:fixed;top:140px; left:0px; z-index:60;">
          </li>
        </a>

        <a href="{% url 'Schedule:rreports' %}">
          <li id="ReportsButton" href="{% url 'Schedule:rreports' %}" style="position:fixed;top:180px; left:0px; z-index:60;">
          </li>
        </a>

        <a href="{% url 'Schedule:rschedule' %}">
          <li id="ScheduleButton" href="{% url 'Schedule:rschedule' %}" style="position:fixed;top:220px;left:0px;z-index:60;">
          </li>
        </a>

          <a href="{% url 'Schedule:raddpatient' %}">
            <li id="AddUsersButton" href="{% url 'Schedule:raddpatient' %}" style="position:fixed;top:260px;left:0px;z-index:60;">
            </li>
          </a>

          <a href="{% url 'Schedule:rpatients' %}">
            <li id="PatientProfiles" href="{% url 'Schedule:rpatients' %}" style="position:fixed;top:300px;left:0px;z-index:60;">
            </li>
          </a>


      </ul>
    </div>
    <div id="TopMenu" class="TopMenu">
      <a class="CurrentUser"> User:Receptionist</a>
      <div id="SettingsMenu">
        <ul>
          <li><img id="HelpPicture" src="{% static 'Schedule/images/HelpSymbol.jpg' %}"><a id="Help" href="#Lock">Help</a></li>
          <li><img id="SettingsPicture" src="{% static 'Schedule/images/settings.jpg' %}"><a id="Settings" href="#Settings">Settings</a></li>
          <li><img id="LogOutPicture" src="{% static 'Schedule/images/logoutSymbol.jpg' %}"> <a id="LogOut" href="#LogOut">Log Out</a></li>
          <li><img id="LockPicture" src="{% static 'Schedule/images/lockSymbol.jpg' %}"><a id="Lock" href="#Lock">Lock</a></li>
        </ul>
      </div>
    </div>
    <div  class="bottomMenu">
      <a id="AddUsers" href="Add Users" style="position:absolute; top:32px; left:120px;">Receptionist DashBoard</a>
      <button id="ReportList">
      </button>
      <div class="Buttons">

        <img src="{% static 'Schedule/images/ReportNavigations.jpg' %}" id="Reports">
        <a href="{% url 'Schedule:rreports' %}">
        <button class="ShowReport" id="GenerateReports" style="position:absolute;                           top:265px;                             left:130px;">
          Generate Reports
        </button>
        </a>

        <img src="{% static 'Schedule/images/PatientProfile.jpg' %}" id="AddUsers">
        <a href="{% url 'Schedule:rpatients' %}">
        <button class="ShowReport" id="Add Patients" style="position:absolute;                           top:265px;                             left:912px;z-index:40">
          Patient Profiles
        </button>
        </a>

        <img src="{% static 'Schedule/images/ScheduleNavigationButton.jpg' %}" id="Schedule">
        <a href="{% url 'Schedule:rhome' %}">
        <button class="ShowReport" id="Schedule" style="position:absolute;                           top:265px;                             left:522px;">
          Schedules
        </button>
        </a>

      </div>
    </div>
  </body>
</html>